#make sure variables below point to the right place / are named appropriately

samplesheet: "config/samples.tsv"

studyName: "tutorial"

#suggest providing an absolute path here for the first time you run the repo, otherwise databases will be recreated every time you use the same primers and database versions which would be a waste of computational power
database_dir: "databases"

rawdatadir: "nativemicrobiota/ocean-data/"

R1file_ending: ".R1.head400.fastq.gz"
R2file_ending: ".R2.head400.fastq.gz"

intstds:
  intstd1: "BP"
  intstd2: "DR"
  intstd3: "TT"

trunclens:
  truncR1: 220
  truncR2: 180

fwdPrimer: "GTGYCAGCMGCCGCGGTAA"
revPrimer: "CCGYCAATTYMTTTRAGTTT"

qiime2version: "../envs/qiime2-amplicon-ubuntu-2024-5-conda.yml" #input name of your yaml file here after the "../env/", and make sure to put it in the workflow/envs/ directory
#sometimes snakemake will fail at creating the environment, in which case you can just provide the name of an existing environment here

#variables below are input for rescript (qiime2) to download databases, change as needed
SILVAversion: "138.1"
