# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"

# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/download_databases.smk"
include: "rules/prepare_bbsplit_db.smk"
include: "rules/00-remove_primers.smk"
include: "rules/01-split-16S-18S.smk"

# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    input:
        get_final_output(),
    default_target: True
